### ISSUE TITLE
    java.lang.NoClassDefFoundError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by mihirmodiofficial** [muxinc/examples#33]
java.lang.NoClassDefFoundError: org.bytedeco.javacpp.avutil
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at org.bytedeco.javacpp.Loader.load(Loader.java:950)
        at org.bytedeco.javacpp.Loader.load(Loader.java:891)
        at org.bytedeco.javacpp.avformat$Write_packet_Pointer_BytePointer_int.<clinit>(avformat.java:640)
        at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:311)
        at com.lakshyacareer.digitalcoaching.activity.LiveStreamActivity.initRecorder(LiveStreamActivity.java:187)
        at com.lakshyacareer.digitalcoaching.activity.LiveStreamActivity.startRecording(LiveStreamActivity.java:210)
        at com.lakshyacareer.digitalcoaching.activity.LiveStreamActivity.onClick(LiveStreamActivity.java:523)
        at android.view.View.performClick(View.java:6612)
        at android.view.View.performClickInternal(View.java:6589)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25925)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by GeneticGenesis** [comment]
Hey @mihirmodiofficial,

Can you give us some more context what you were doing when you received this error that might help us reproduce it, or even which example you got it in?

Thanks.

**Comment by mihirmodiofficial** [comment]
Configuration 
Android Studio 4.0
Gradle plugin 6.1.1

Device
Android 9.0

Simply run the app and click on start button

Please Use Camera 2 Api or Camerax older one is already deprecated.

**Comment by mobiledev1221** [comment]
I got the same issue. 
@mihirmodiofficial did you fix it?

**Comment by GeneticGenesis** [comment]
Thanks for the feedback on the Android example. 

I've not been immediately able to reproduce this on our end in the same configuration, and we do use this example for regression testing frequently.

We're actively working to replace our iOS and Android examples with more up-to-date approaches, and will have something to share in the coming months. 

Thanks.

**Comment by mobiledev1221** [comment]
I have fixed it. 
In my case, it is because my device has 64bit processors and it generates and check arm64 folder to load native library. So I added ndk filters to avoid that issue.

```
defaultConfig {
    ...

    ndk {
        abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
    }

}
``

I hope this would help other ones.

**Comment by GeneticGenesis** [comment]
Hey @mobiledev1221, just to let you know we've now replaced the Android example with something more modern, please let us know if you have any feedback or issues!

Thanks!
